apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: voting-app
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
        - secretRef:
            name: db-secret
        ports:
        - containerPort: 5432