apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: omniasaad/vote:v1
        envFrom:
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 80